### ISSUE TITLE
gulpfile.js file missing

### ISSUE THREAD

**Issue by georgemeng-cfwt** [coldbox-templates/elixir-vuejs#23]
In the **ColdBox Elixir Installation** section, the document says "You will find a package.json and a Gulpfile.js in the root of this template."

But I double checked and did not find Gulpfile.js in this template. Did I miss anything?

Thanks!

George

**Comment by lmajano** [comment]
You are right, we need to update the docs on this. It has changed through time.

**Comment by lmajano** [comment]
Updated now
https://github.com/coldbox-templates/elixir-vuejs/blob/master/readme.md
